In [ ]:
# Update sklearn to prevent version mismatches
!pip install sklearn --upgrade

In [ ]:
# install joblib. This will be used to save your model. 
# Restart your kernel after installing 
!pip install joblib

In [2]:
import pandas as pd

# Read the CSV and Perform Basic Data Cleaning

In [3]:
exoplanet_df = pd.read_csv("../Resources/data/exoplanets.csv")

# Drop the null columns where all values are null
exoplanet_df = exoplanet_df.dropna(axis='columns', how='all')

# Drop the null rows
exoplanet_df = exoplanet_df.dropna()
exoplanet_df.head()

rowid     kepid kepoi_name   kepler_name koi_disposition koi_pdisposition  \
0      1  10797460  K00752.01  Kepler-227 b       CONFIRMED        CANDIDATE   
1      2  10797460  K00752.02  Kepler-227 c       CONFIRMED        CANDIDATE   
4      5  10854555  K00755.01  Kepler-664 b       CONFIRMED        CANDIDATE   
5      6  10872983  K00756.01  Kepler-228 d       CONFIRMED        CANDIDATE   
6      7  10872983  K00756.02  Kepler-228 c       CONFIRMED        CANDIDATE   

   koi_score  koi_fpflag_nt  koi_fpflag_ss  koi_fpflag_co  ...  \
0      1.000              0              0              0  ...   
1      0.969              0              0              0  ...   
4      1.000              0              0              0  ...   
5      1.000              0              0              0  ...   
6      1.000              0              0              0  ...   

   koi_steff_err2  koi_slogg  koi_slogg_err1  koi_slogg_err2  koi_srad  \
0           -81.0      4.467           0.064          -0.096     0.927   
1           -81.0      4.467           0.064          -0.096     0.927   
4          -211.0      4.438           0.070          -0.210     1.046   
5          -232.0      4.486           0.054          -0.229     0.972   
6          -232.0      4.486           0.054          -0.229     0.972   

   koi_srad_err1  koi_srad_err2         ra        dec  koi_kepmag  
0          0.105         -0.061  291.93423  48.141651      15.347  
1          0.105         -0.061  291.93423  48.141651      15.347  
4          0.334         -0.133  288.75488  48.226200      15.509  
5          0.315         -0.105  296.28613  48.224670      15.714  
6          0.315         -0.105  296.28613  48.224670      15.714  

[5 rows x 48 columns]

In [4]:
exoplanet_df.shape

(2269, 48)

# Select your features (columns)

In [6]:
exoplanet_df.columns

Index(['rowid', 'kepid', 'kepoi_name', 'kepler_name', 'koi_disposition',
       'koi_pdisposition', 'koi_score', 'koi_fpflag_nt', 'koi_fpflag_ss',
       'koi_fpflag_co', 'koi_fpflag_ec', 'koi_period', 'koi_period_err1',
       'koi_period_err2', 'koi_time0bk', 'koi_time0bk_err1',
       'koi_time0bk_err2', 'koi_impact', 'koi_impact_err1', 'koi_impact_err2',
       'koi_duration', 'koi_duration_err1', 'koi_duration_err2', 'koi_depth',
       'koi_depth_err1', 'koi_depth_err2', 'koi_prad', 'koi_prad_err1',
       'koi_prad_err2', 'koi_teq', 'koi_insol', 'koi_insol_err1',
       'koi_insol_err2', 'koi_model_snr', 'koi_tce_plnt_num',
       'koi_tce_delivname', 'koi_steff', 'koi_steff_err1', 'koi_steff_err2',
       'koi_slogg', 'koi_slogg_err1', 'koi_slogg_err2', 'koi_srad',
       'koi_srad_err1', 'koi_srad_err2', 'ra', 'dec', 'koi_kepmag'],
      dtype='object')

In [28]:
# Set features. This will also be used as your x values.
X = exoplanet_df[['koi_score', 
                  'koi_fpflag_nt', 
                  'koi_fpflag_ss', 
                  'koi_fpflag_co', 
                  'koi_fpflag_ec', 
                  'koi_period', 
                  'koi_time0bk', 
                  'koi_impact', 
                  'koi_duration', 
                  'koi_depth' ,
                  'koi_prad', 
                  'koi_teq', 
                  'koi_insol', 
                  'koi_model_snr', 
                  'koi_steff', 
                  'koi_slogg', 
                  'koi_srad', 
                  'ra', 
                  'dec', 
                  'koi_kepmag']]
X.shape

(2269, 20)

In [29]:
X.head()

koi_score  koi_fpflag_nt  koi_fpflag_ss  koi_fpflag_co  koi_fpflag_ec  \
0      1.000              0              0              0              0   
1      0.969              0              0              0              0   
4      1.000              0              0              0              0   
5      1.000              0              0              0              0   
6      1.000              0              0              0              0   

   koi_period  koi_time0bk  koi_impact  koi_duration  koi_depth  koi_prad  \
0    9.488036    170.53875       0.146        2.9575      615.8      2.26   
1   54.418383    162.51384       0.586        4.5070      874.8      2.83   
4    2.525592    171.59555       0.701        1.6545      603.3      2.75   
5   11.094321    171.20116       0.538        4.5945     1517.5      3.90   
6    4.134435    172.97937       0.762        3.1402      686.0      2.77   

   koi_teq  koi_insol  koi_model_snr  koi_steff  koi_slogg  koi_srad  \
0    793.0      93.59           35.8     5455.0      4.467     0.927   
1    443.0       9.11           25.8     5455.0      4.467     0.927   
4   1406.0     926.16           40.9     6031.0      4.438     1.046   
5    835.0     114.81           66.5     6046.0      4.486     0.972   
6   1160.0     427.65           40.2     6046.0      4.486     0.972   

          ra        dec  koi_kepmag  
0  291.93423  48.141651      15.347  
1  291.93423  48.141651      15.347  
4  288.75488  48.226200      15.509  
5  296.28613  48.224670      15.714  
6  296.28613  48.224670      15.714

Use `koi_disposition` for the y values

In [30]:
y = exoplanet_df['koi_disposition'].values.reshape(-1,1)
y.shape

(2269, 1)

# Create a Train Test Split


In [31]:
from sklearn.model_selection import train_test_split

In [32]:
X_train, X_leftover, y_train, y_leftover = train_test_split(X, y, test_size = 0.3)
X_test, X_val, y_test, y_val = train_test_split(X_leftover, y_leftover, test_size = 0.2)

In [33]:
X_train.head()

koi_score  koi_fpflag_nt  koi_fpflag_ss  koi_fpflag_co  koi_fpflag_ec  \
3417       1.00              0              0              0              0   
97         0.95              0              0              0              0   
1639       1.00              0              0              0              0   
258        1.00              0              0              0              0   
2210       1.00              0              0              0              0   

      koi_period  koi_time0bk  koi_impact  koi_duration  koi_depth  koi_prad  \
3417    8.594819   171.627810       0.617        3.2540      336.5      1.75   
97      6.164876   135.639160       0.646        3.2620       55.8      0.79   
1639    9.304139   140.338680       0.488        1.9254      637.3      1.67   
258    17.648309   133.545330       0.653        2.0873      763.3      2.43   
2210    9.549277   175.757183       0.068        1.5832     1826.9      1.57   

      koi_teq  koi_insol  koi_model_snr  koi_steff  koi_slogg  koi_srad  \
3417    854.0     125.48           37.5     5675.0      4.459     0.915   
97     1021.0     256.35           14.4     5854.0      4.406     1.012   
1639    583.0      27.35           24.2     4458.0      4.611     0.658   
258     579.0      26.49           23.8     5029.0      4.494     0.838   
2210    374.0       4.62          112.2     3547.0      4.899     0.369   

             ra        dec  koi_kepmag  
3417  284.40991  41.237461      13.984  
97    300.86398  44.337551      12.882  
1639  283.89941  41.221611      14.796  
258   289.59476  44.141949      15.460  
2210  284.92184  45.972401      14.486

# Pre-processing

Scale the data using the MinMaxScaler and perform some feature selection

In [34]:
# Scale your data
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
scaler.fit(X_train)
X_train_scaled = scaler.transform(X_train)

In [35]:
print(X_train_scaled)

[[1.         0.         0.         ... 0.19537412 0.299265   0.62263539]
 [0.95       0.         0.         ... 0.960176   0.49834922 0.50351313]
 [1.         0.         0.         ... 0.17164556 0.29824713 0.71040969]
 ...
 [0.982      0.         0.         ... 0.04209971 0.42708171 0.40525349]
 [0.996      0.         0.         ... 0.43236083 0.33616887 0.82423522]
 [0.985      0.         0.         ... 0.70294308 0.38258902 0.76834937]]


# Train the Model



In [36]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:


# Create a random forest classifier
rf = RandomForestClassifier()
rf = rf.fit(X_train, y_train)
print(rf.score(X_t, y_t), rf.score(X_v, y_v))

In [ ]:
print(f"Training Data Score: {model2.score(X_train_scaled, y_train)}")
print(f"Testing Data Score: {model2.score(X_test_scaled, y_test)}")

# Hyperparameter Tuning

Use `GridSearchCV` to tune the model's parameters

In [ ]:
# Create the GridSearchCV model

In [ ]:
# Train the model with GridSearch

In [ ]:
print(grid2.best_params_)
print(grid2.best_score_)

# Save the Model

In [ ]:
# save your model by updating "your_name" with your name
# and "your_model" with your model variable
# be sure to turn this in to BCS
# if joblib fails to import, try running the command to install in terminal/git-bash
import joblib
filename = 'your_name.sav'
joblib.dump(your_model, filename)